ALTER TABLE IF EXISTS "session" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "session_log" DISABLE ROW LEVEL SECURITY;
DROP TABLE IF EXISTS "session" CASCADE;
DROP TABLE IF EXISTS "session_log" CASCADE;
DROP INDEX IF EXISTS "thread_current_session_idx";
ALTER TABLE "thread" DROP COLUMN IF EXISTS "current_session_id";
