//! GENERATED by scripts/browser-addon-pins.mjs. Do not edit by hand.
//!
//! Pinned, checksummed downloads for `bud browser prepare`. Versions derive
//! from bud/browser-helper (playwright-core pin and its browsers.json), so the
//! daemon, helper and managed browser agree by construction.

/// Managed Node runtime version (nodejs.org dist).
pub const NODE_VERSION: &str = "v24.21.0";
/// playwright-core version vendored into the helper.
pub const PLAYWRIGHT_CORE_VERSION: &str = "1.63.0";
/// Chrome for Testing build that playwright-core 1.63.0 installs and tests against.
pub const MANAGED_BROWSER_VERSION: &str = "153.0.8010.12";
/// Minimum Chromium major accepted for a system browser: Playwright's own.
pub const BROWSER_MIN_MAJOR: u32 = 153;

pub struct Artifact {
    pub target: &'static str,
    pub url: &'static str,
    pub sha256: &'static str,
    pub size: u64,
    /// Executable path relative to the extraction directory.
    pub executable: &'static str,
}

pub const NODE: &[Artifact] = &[
    Artifact {
        target: "aarch64-apple-darwin",
        url: "https://nodejs.org/dist/v24.21.0/node-v24.21.0-darwin-arm64.tar.gz",
        sha256: "bed7eea5325e1108f32ce5228ddd6a5f0f08a499ee42aa7442aea583702f6057",
        size: 52909993,
        executable: "node-v24.21.0-darwin-arm64/bin/node",
    },
    Artifact {
        target: "x86_64-apple-darwin",
        url: "https://nodejs.org/dist/v24.21.0/node-v24.21.0-darwin-x64.tar.gz",
        sha256: "1462cb3b3046b815cf8ea436d3da450ec1a9f11dac7e5a46b0ada5305d7e8097",
        size: 54203979,
        executable: "node-v24.21.0-darwin-x64/bin/node",
    },
    Artifact {
        target: "x86_64-unknown-linux-gnu",
        url: "https://nodejs.org/dist/v24.21.0/node-v24.21.0-linux-x64.tar.gz",
        sha256: "6e1db87ef58b8819e5d5402eff1536491b18edd8eb7bee5ef7897876e88dc5ff",
        size: 58088022,
        executable: "node-v24.21.0-linux-x64/bin/node",
    },
    Artifact {
        target: "aarch64-unknown-linux-gnu",
        url: "https://nodejs.org/dist/v24.21.0/node-v24.21.0-linux-arm64.tar.gz",
        sha256: "724282c3b43aec998aa9527380465b45d229e021b58035f5f4f63095eabfe5d5",
        size: 57824078,
        executable: "node-v24.21.0-linux-arm64/bin/node",
    },
];

pub const MANAGED_BROWSER: &[Artifact] = &[
    Artifact { target: "aarch64-apple-darwin", url: "https://cdn.playwright.dev/builds/cft/153.0.8010.12/mac-arm64/chrome-mac-arm64.zip", sha256: "930e2a2c15addbaca1fe9b07bfa520667bced556d7988707186819cb4279ef3b", size: 190970181, executable: "chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing" },
    Artifact { target: "x86_64-apple-darwin", url: "https://cdn.playwright.dev/builds/cft/153.0.8010.12/mac-x64/chrome-mac-x64.zip", sha256: "4e12e2b8a297a2eb79c16258e46961c73f8aa2fa6be6b1d3cdbb553fb5d4ef1c", size: 201663099, executable: "chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing" },
    Artifact { target: "x86_64-unknown-linux-gnu", url: "https://cdn.playwright.dev/builds/cft/153.0.8010.12/linux64/chrome-linux64.zip", sha256: "8aac35011c18f6e2d10696154af89a5728ac2ddd6dc6fad24ffdf243c3fcfd5a", size: 195836009, executable: "chrome-linux64/chrome" },
    Artifact { target: "aarch64-unknown-linux-gnu", url: "https://cdn.playwright.dev/builds/cft/153.0.8010.12/linux-arm64/chrome-linux-arm64.zip", sha256: "7d8a4b4ff289efe44a06501a519df142c4c18fff7aaf1c1401a3fbb12b3bd069", size: 195926016, executable: "chrome-linux-arm64/chrome" },
];
