name = "get-bud-dev"
main = "worker.js"
compatibility_date = "2026-05-30"

[assets]
directory = "./assets"
binding = "ASSETS"
run_worker_first = true

[observability.logs]
enabled = true

[[routes]]
pattern = "get.bud.dev"
custom_domain = true
