import test from 'node:test';
import assert from 'node:assert/strict';
import Fastify from 'fastify';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { beginAgentCapture, registerAgentCaptures } from './agent-capture.js';
import { ImageArtifacts } from './image-artifacts.js';
import type { BrowserCarrier, BrowserCommand } from './transport.js';

test('capture is single-use, bounded, owned and revoked before publication', async t => {
  const path = await mkdtemp(join(tmpdir(), 'bud-capture-'));
  const images = new ImageArtifacts(path);
  const server = Fastify();
  t.after(async () => { await server.close(); await rm(path, { recursive:true, force:true }); });
  let allowed = true, current = true;
  await registerAgentCaptures(server, { evidenceAllowed: async () => allowed }, images);
  const carrier = { current: () => current } as BrowserCarrier;
  const request = { request_id:'request', owner_user_id:'alice', thread_id:'thread', session_id:'session', generation:'generation', control_epoch:1, expires_at_ms:Date.now()+10000 } as BrowserCommand;
  const frame = { target_id:'target', document_id:'document', image:'iVBORw0KGgo=', image_format:'png' };
  const upload = (ticket: string, payload: Record<string, unknown> = frame) => server.inject({ method:'POST', url:'/api/browser/captures', headers:{authorization:`Bearer ${ticket}`}, payload });
  const grant = () => beginAgentCapture(request, carrier, 'call', 'bud', 'target');
  const first = grant();
  const response = await upload(first.command.ticket);
  assert.equal(response.statusCode,200);
  assert.doesNotMatch(response.body,/iVBOR/);
  const stored = await images.get(response.json().image_artifact.id,'alice','thread','call');
  assert.equal(stored?.image,frame.image);
  assert.equal(await images.get(response.json().image_artifact.id,'bob','thread'),null);
  assert.equal((await upload(first.command.ticket)).statusCode,403);
  assert.equal((await upload(grant().command.ticket,{...frame,target_id:'foreign'})).statusCode,400);
  assert.equal((await upload(grant().command.ticket,{...frame,image:'not an image'})).statusCode,400);
  assert.equal((await upload(grant().command.ticket,{...frame,image:'x'.repeat(1_430_000)})).statusCode,413);
  allowed = false;
  assert.equal((await upload(grant().command.ticket)).statusCode,403);
  allowed = true; current = false;
  assert.equal((await upload(grant().command.ticket)).statusCode,403);
  current = true;
  const revoked = grant(); revoked.dispose();
  assert.equal((await upload(revoked.command.ticket)).statusCode,403);
});
