import test from 'node:test';
import assert from 'node:assert/strict';
import Fastify from 'fastify';
import websocket from '@fastify/websocket';
import {auth} from '../auth/auth.js';
import {db} from '../db/client.js';
import {config} from '../config.js';
import {BrowserStateEvents} from './state-events.js';
import {BrowserMobileAuth,mobileCookie} from './mobile-auth.js';
import {BrowserControl} from './control.js';
import {BrowserError} from './repository.js';
import {registerBrowserRoutes} from './routes.js';

test('state routes deny anonymous/foreign and out-of-scope mobile viewers before subscription',async t=>{
  const server=Fastify();
  t.after(async()=>{await server.close();t.mock.restoreAll();});
  t.mock.method(BrowserStateEvents.prototype,'ready',async()=>{});
  const subscribe=t.mock.method(BrowserStateEvents.prototype,'subscribe',()=>()=>{});
  let loggedIn=false;
  t.mock.method(auth.api,'getSession',async()=>loggedIn?{user:{id:'alice'},session:{id:'auth'}} as never:null);
  t.mock.method(db,'select',()=>({from:()=>({where:()=>({limit:async()=>[{id:'auth'}]})})}) as never);
  t.mock.method(db.query.threadTable,'findFirst',async()=>null);
  t.mock.method(db.query.budTable,'findFirst',async()=>null);
  const get=t.mock.fn(async()=>{throw new BrowserError('browser_not_found');});
  const control=new BrowserControl({get} as never);
  await server.register(websocket);
  await registerBrowserRoutes(server,control,{} as never);
  const thread='00000000-0000-4000-8000-000000000001';
  const paths=[`/api/threads/${thread}/browser-state`,'/api/browser/sessions/foreign/state','/api/buds/foreign/browser/state'];
  const headers={origin:config.betterAuthTrustedOrigins[0],upgrade:'websocket',connection:'upgrade'};
  for(const url of paths)assert.equal((await server.inject({url,headers})).statusCode,401);
  loggedIn=true;
  for(const url of paths)assert.equal((await server.inject({url,headers})).statusCode,404);
  assert.equal(subscribe.mock.callCount(),0);
  t.mock.method(BrowserMobileAuth.prototype,'resolve',async()=>({created_by_user_id:'alice',session_id:'allowed',viewer_id:'viewer',id:'visit'}) as never);
  const before=get.mock.callCount();
  for(const url of paths) assert.equal((await server.inject({url,headers:{...headers,cookie:`${mobileCookie}=token`}})).statusCode,404);
  assert.equal(get.mock.callCount(),before,'mobile scope rejects before reading a different workspace');
  assert.equal(subscribe.mock.callCount(),0);
});
