/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BudIdRouteImport } from './routes/$budId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudIdIndexRouteImport } from './routes/$budId/index'
import { Route as AuthMobileRouteImport } from './routes/auth.mobile'
import { Route as BudIdNewRouteImport } from './routes/$budId/new'
import { Route as BudIdThreadIdRouteImport } from './routes/$budId/$threadId'
import { Route as DevicesClaimFlowIdRouteImport } from './routes/devices.claim.$flowId'
import { Route as AuthMobileConsentRouteImport } from './routes/auth.mobile.consent'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BudIdRoute = BudIdRouteImport.update({
  id: '/$budId',
  path: '/$budId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudIdIndexRoute = BudIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudIdRoute,
} as any)
const AuthMobileRoute = AuthMobileRouteImport.update({
  id: '/auth/mobile',
  path: '/auth/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const BudIdNewRoute = BudIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BudIdRoute,
} as any)
const BudIdThreadIdRoute = BudIdThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => BudIdRoute,
} as any)
const DevicesClaimFlowIdRoute = DevicesClaimFlowIdRouteImport.update({
  id: '/devices/claim/$flowId',
  path: '/devices/claim/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMobileConsentRoute = AuthMobileConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthMobileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$budId': typeof BudIdRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/$budId/$threadId': typeof BudIdThreadIdRoute
  '/$budId/new': typeof BudIdNewRoute
  '/auth/mobile': typeof AuthMobileRouteWithChildren
  '/$budId/': typeof BudIdIndexRoute
  '/auth/mobile/consent': typeof AuthMobileConsentRoute
  '/devices/claim/$flowId': typeof DevicesClaimFlowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/$budId/$threadId': typeof BudIdThreadIdRoute
  '/$budId/new': typeof BudIdNewRoute
  '/auth/mobile': typeof AuthMobileRouteWithChildren
  '/$budId': typeof BudIdIndexRoute
  '/auth/mobile/consent': typeof AuthMobileConsentRoute
  '/devices/claim/$flowId': typeof DevicesClaimFlowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$budId': typeof BudIdRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/$budId/$threadId': typeof BudIdThreadIdRoute
  '/$budId/new': typeof BudIdNewRoute
  '/auth/mobile': typeof AuthMobileRouteWithChildren
  '/$budId/': typeof BudIdIndexRoute
  '/auth/mobile/consent': typeof AuthMobileConsentRoute
  '/devices/claim/$flowId': typeof DevicesClaimFlowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$budId'
    | '/login'
    | '/settings'
    | '/$budId/$threadId'
    | '/$budId/new'
    | '/auth/mobile'
    | '/$budId/'
    | '/auth/mobile/consent'
    | '/devices/claim/$flowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/$budId/$threadId'
    | '/$budId/new'
    | '/auth/mobile'
    | '/$budId'
    | '/auth/mobile/consent'
    | '/devices/claim/$flowId'
  id:
    | '__root__'
    | '/'
    | '/$budId'
    | '/login'
    | '/settings'
    | '/$budId/$threadId'
    | '/$budId/new'
    | '/auth/mobile'
    | '/$budId/'
    | '/auth/mobile/consent'
    | '/devices/claim/$flowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudIdRoute: typeof BudIdRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AuthMobileRoute: typeof AuthMobileRouteWithChildren
  DevicesClaimFlowIdRoute: typeof DevicesClaimFlowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$budId': {
      id: '/$budId'
      path: '/$budId'
      fullPath: '/$budId'
      preLoaderRoute: typeof BudIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$budId/': {
      id: '/$budId/'
      path: '/'
      fullPath: '/$budId/'
      preLoaderRoute: typeof BudIdIndexRouteImport
      parentRoute: typeof BudIdRoute
    }
    '/auth/mobile': {
      id: '/auth/mobile'
      path: '/auth/mobile'
      fullPath: '/auth/mobile'
      preLoaderRoute: typeof AuthMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$budId/new': {
      id: '/$budId/new'
      path: '/new'
      fullPath: '/$budId/new'
      preLoaderRoute: typeof BudIdNewRouteImport
      parentRoute: typeof BudIdRoute
    }
    '/$budId/$threadId': {
      id: '/$budId/$threadId'
      path: '/$threadId'
      fullPath: '/$budId/$threadId'
      preLoaderRoute: typeof BudIdThreadIdRouteImport
      parentRoute: typeof BudIdRoute
    }
    '/devices/claim/$flowId': {
      id: '/devices/claim/$flowId'
      path: '/devices/claim/$flowId'
      fullPath: '/devices/claim/$flowId'
      preLoaderRoute: typeof DevicesClaimFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mobile/consent': {
      id: '/auth/mobile/consent'
      path: '/consent'
      fullPath: '/auth/mobile/consent'
      preLoaderRoute: typeof AuthMobileConsentRouteImport
      parentRoute: typeof AuthMobileRoute
    }
  }
}

interface BudIdRouteChildren {
  BudIdThreadIdRoute: typeof BudIdThreadIdRoute
  BudIdNewRoute: typeof BudIdNewRoute
  BudIdIndexRoute: typeof BudIdIndexRoute
}

const BudIdRouteChildren: BudIdRouteChildren = {
  BudIdThreadIdRoute: BudIdThreadIdRoute,
  BudIdNewRoute: BudIdNewRoute,
  BudIdIndexRoute: BudIdIndexRoute,
}

const BudIdRouteWithChildren = BudIdRoute._addFileChildren(BudIdRouteChildren)

interface AuthMobileRouteChildren {
  AuthMobileConsentRoute: typeof AuthMobileConsentRoute
}

const AuthMobileRouteChildren: AuthMobileRouteChildren = {
  AuthMobileConsentRoute: AuthMobileConsentRoute,
}

const AuthMobileRouteWithChildren = AuthMobileRoute._addFileChildren(
  AuthMobileRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudIdRoute: BudIdRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AuthMobileRoute: AuthMobileRouteWithChildren,
  DevicesClaimFlowIdRoute: DevicesClaimFlowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
