/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BudIdRouteImport } from './routes/$budId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudIdIndexRouteImport } from './routes/$budId/index'
import { Route as BudIdNewRouteImport } from './routes/$budId/new'
import { Route as BudIdThreadIdRouteImport } from './routes/$budId/$threadId'

const BudIdRoute = BudIdRouteImport.update({
  id: '/$budId',
  path: '/$budId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudIdIndexRoute = BudIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudIdRoute,
} as any)
const BudIdNewRoute = BudIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BudIdRoute,
} as any)
const BudIdThreadIdRoute = BudIdThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => BudIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$budId': typeof BudIdRouteWithChildren
  '/$budId/$threadId': typeof BudIdThreadIdRoute
  '/$budId/new': typeof BudIdNewRoute
  '/$budId/': typeof BudIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$budId/$threadId': typeof BudIdThreadIdRoute
  '/$budId/new': typeof BudIdNewRoute
  '/$budId': typeof BudIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$budId': typeof BudIdRouteWithChildren
  '/$budId/$threadId': typeof BudIdThreadIdRoute
  '/$budId/new': typeof BudIdNewRoute
  '/$budId/': typeof BudIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$budId' | '/$budId/$threadId' | '/$budId/new' | '/$budId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$budId/$threadId' | '/$budId/new' | '/$budId'
  id:
    | '__root__'
    | '/'
    | '/$budId'
    | '/$budId/$threadId'
    | '/$budId/new'
    | '/$budId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudIdRoute: typeof BudIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$budId': {
      id: '/$budId'
      path: '/$budId'
      fullPath: '/$budId'
      preLoaderRoute: typeof BudIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$budId/': {
      id: '/$budId/'
      path: '/'
      fullPath: '/$budId/'
      preLoaderRoute: typeof BudIdIndexRouteImport
      parentRoute: typeof BudIdRoute
    }
    '/$budId/new': {
      id: '/$budId/new'
      path: '/new'
      fullPath: '/$budId/new'
      preLoaderRoute: typeof BudIdNewRouteImport
      parentRoute: typeof BudIdRoute
    }
    '/$budId/$threadId': {
      id: '/$budId/$threadId'
      path: '/$threadId'
      fullPath: '/$budId/$threadId'
      preLoaderRoute: typeof BudIdThreadIdRouteImport
      parentRoute: typeof BudIdRoute
    }
  }
}

interface BudIdRouteChildren {
  BudIdThreadIdRoute: typeof BudIdThreadIdRoute
  BudIdNewRoute: typeof BudIdNewRoute
  BudIdIndexRoute: typeof BudIdIndexRoute
}

const BudIdRouteChildren: BudIdRouteChildren = {
  BudIdThreadIdRoute: BudIdThreadIdRoute,
  BudIdNewRoute: BudIdNewRoute,
  BudIdIndexRoute: BudIdIndexRoute,
}

const BudIdRouteWithChildren = BudIdRoute._addFileChildren(BudIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudIdRoute: BudIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
